# Generated by Django 3.2.21 on 2023-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintananceRequest',
            fields=[
                ('maintanance', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('maintanance_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintanance_request',
                'managed': False,
            },
        ),
    ]
