# Generated by Django 3.2.21 on 2023-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=45)),
                ('house_name', models.CharField(max_length=45)),
                ('landmark', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('pincode', models.CharField(max_length=45)),
                ('mob_no', models.CharField(max_length=45)),
                ('email_id', models.CharField(max_length=45)),
                ('id_proof', models.CharField(max_length=200)),
                ('professional_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tenant',
                'managed': False,
            },
        ),
    ]
