# Generated by Django 3.2.21 on 2023-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('required_year', models.CharField(max_length=45)),
                ('required_month', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=45)),
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'property_request',
                'managed': False,
            },
        ),
    ]
