# Generated by Django 3.2.21 on 2023-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaySecurity',
            fields=[
                ('security_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('card_no', models.CharField(max_length=45)),
                ('cvv', models.CharField(max_length=45)),
                ('amount', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pay_security',
                'managed': False,
            },
        ),
    ]
